### ISSUE TITLE
Support feeds without item titles

### ISSUE THREAD

**Issue by 92Julian** [adamsanderson/brook#3]
The sidebar turns blank when I open a feed without item titles.
Example: http://www.dosisdiarias.com/

**Comment by adamsanderson** [comment]
Thanks for reporting that, I'll have to ponder what to use instead of the title in that case.

**Comment by 92Julian** [comment]
Thanks, now all my feeds are working.

> I'll have to ponder what to use instead of the title in that case.

Firefox [live bookmarks](https://support.mozilla.org/en-US/kb/live-bookmarks) and [Brief](https://addons.mozilla.org/en-US/firefox/addon/brief/) use the URLs instead of the title for items without titles.
