### ISSUE TITLE
Excessive memory usage

### ISSUE THREAD

**Issue by 92Julian** [adamsanderson/brook#4]
During automatic update of feeds memory usage rise excessively.

![captura de pantalla de 2018-12-26 14-46-50](https://user-images.githubusercontent.com/25293942/50494843-67da0880-0a04-11e9-9990-09e967731176.png)

Normally all Firefox process  are under 200 MiB.

OS: Ubuntu 18.10
Firefox: 65.0b6
Brook: 0.2.3
I'm subscribed to 50 feeds.

**Comment by adamsanderson** [comment]
Thank you for reporting this.  I'll be honest, I'm not sure how best to track this down, the profiling and development tools are not great for firefox extensions, though I will see what I can do.

Does the memory usage return to normal shortly after automatic updates have finished?

**Comment by adamsanderson** [comment]
I've done a bit of digging, and while there are some obvious places where more memory allocations occur than are probably needed (ie: `Feed.js`'s calls to `react-fast-compare`) they only account for about a 1.6mb of memory usage.  I suspect there is something more going on that is not captured in the profiling such as overhead from calling `postMessage` to synchronize the store, etc.

I will dedicate some more time to debugging this later, but I'm afraid it may be very hard to track down.

**Comment by 92Julian** [comment]
> Does the memory usage return to normal shortly after automatic updates have finished?

Only the WebExtensions process, the main Firefox process and Web Content processes need interaction (open/close the sidebar and tabs) to return to normal.

Looks like the amount of memory Brook take depends on the number of open tabs:
![captura de pantalla de 2018-12-30 23-31-53](https://user-images.githubusercontent.com/25293942/50554047-573ec200-0c92-11e9-938b-c3ce50a47a5e.png)
![captura de pantalla de 2018-12-30 23-33-55](https://user-images.githubusercontent.com/25293942/50554049-5c037600-0c92-11e9-90fe-099ef551dd6f.png)

**Comment by adamsanderson** [comment]
Interesting… That actually helps a lot. 

I suspect it's some overhead in the messaging between tabs, the background script, and the sidebar.  The tabs really don't need to participate in the full messaging system so I think I can bypass a lot of that.

Thanks again, and thanks for helping me make this better.  You most likely account for about 10% of all active users so I appreciate it all the more ;)

**Comment by adamsanderson** [comment]
I've been able to isolate the issue.  It does look like this was related to the message passing between tabs (content scripts) and they try to recreate the entire extension state for each script.  I've introduced a cheaper dispatch strategy that _drastically_ cuts that down.

I'll bundle this up and release it shortly.  Thanks again for reporting the problem.

**Comment by adamsanderson** [comment]
Shipped in 0.2.4.
